"""agrego attr a comprobnates

Revision ID: 0e2209bdb4f1
Revises: 90f4b178864c
Create Date: 2025-06-23 22:34:04.980570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e2209bdb4f1'
down_revision: Union[str, None] = '90f4b178864c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column("comprobante", sa.Column("cae", sa.String(length=50), nullable=True))
    op.add_column("comprobante", sa.Column("cae_vencimiento", sa.Date(), nullable=True))



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comprobante', 'cae_vencimiento')
    op.drop_column('comprobante', 'cae')
    # ### end Alembic commands ###
