"""Agregar codigo_arca a tipocomprobante

Revision ID: 2c926e8e24a7
Revises: 
Create Date: 2025-06-17 22:39:01.051399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c926e8e24a7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tipocomprobante', sa.Column('codigo_arca', sa.String(length=3), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tipocomprobante', 'codigo_arca')
    # ### end Alembic commands ###
