"""add_ambito_to_condicion_tributaria

Revision ID: 36f8df1fb5f4
Revises: ecdb8ab51ad1
Create Date: 2025-12-29 17:49:08.535480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36f8df1fb5f4'
down_revision: Union[str, None] = 'ecdb8ab51ad1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('condiciontributaria', sa.Column('ambito', sa.Enum('NACIONAL', 'PROVINCIAL', 'MUNICIPAL', name='ambitoimpuestoenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('condiciontributaria', 'ambito')
    # ### end Alembic commands ###
