"""align_tipoimpuesto_with_odoo

Revision ID: 5747e1cd6477
Revises: 8f307b814a9a
Create Date: 2025-12-29 23:41:22.107289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5747e1cd6477'
down_revision: Union[str, None] = '8f307b814a9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tipoimpuesto', sa.Column('tipo_uso', sa.Enum('VENTAS', 'COMPRAS', 'OTRO', 'RETENCION_PAGO_PROVEEDOR', 'RETENCION_PAGO_CLIENTE', name='tipousoimpuestoenum'), nullable=False))
    op.add_column('tipoimpuesto', sa.Column('metodo_calculo', sa.Enum('PORCENTAJE', 'FIJO', 'PORCENTAJE_SOBRE_PRECIO', 'GRUPO', name='metodocalculoimpuestoenum'), nullable=False))
    op.add_column('tipoimpuesto', sa.Column('ambito_uso', sa.Enum('BIENES', 'SERVICIOS', 'AMBOS', name='ambitousoimpuestoenum'), nullable=False))
    op.add_column('tipoimpuesto', sa.Column('importe', sa.Float(), nullable=False))
    op.add_column('tipoimpuesto', sa.Column('etiqueta_factura', sa.String(length=50), nullable=True))
    op.add_column('tipoimpuesto', sa.Column('incluido_precio', sa.Boolean(), nullable=False))
    op.add_column('tipoimpuesto', sa.Column('afecta_base_subsecuente', sa.Boolean(), nullable=False))
    op.add_column('tipoimpuesto', sa.Column('categoria_fiscal', sa.Enum('AE', 'E', 'S', 'Z', 'G', 'O', 'K', 'L', 'M', 'B', name='categoriafiscalimpuestoenum'), nullable=True))
    op.add_column('tipoimpuesto', sa.Column('notas_legales', sa.Text(), nullable=True))
    op.add_column('tipoimpuesto', sa.Column('cuenta_impuesto_vta', sa.String(length=100), nullable=True))
    op.add_column('tipoimpuesto', sa.Column('cuenta_impuesto_com', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tipoimpuesto', 'cuenta_impuesto_com')
    op.drop_column('tipoimpuesto', 'cuenta_impuesto_vta')
    op.drop_column('tipoimpuesto', 'notas_legales')
    op.drop_column('tipoimpuesto', 'categoria_fiscal')
    op.drop_column('tipoimpuesto', 'afecta_base_subsecuente')
    op.drop_column('tipoimpuesto', 'incluido_precio')
    op.drop_column('tipoimpuesto', 'etiqueta_factura')
    op.drop_column('tipoimpuesto', 'importe')
    op.drop_column('tipoimpuesto', 'ambito_uso')
    op.drop_column('tipoimpuesto', 'metodo_calculo')
    op.drop_column('tipoimpuesto', 'tipo_uso')
    # ### end Alembic commands ###
