"""collapse_client_tax_fields

Revision ID: 8f307b814a9a
Revises: a05fa68eda88
Create Date: 2025-12-29 21:52:18.460664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8f307b814a9a'
down_revision: Union[str, None] = 'a05fa68eda88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clienteimpuesto')
    op.add_column('cliente', sa.Column('condicion_iva_id', sa.Integer(), nullable=True))
    op.add_column('cliente', sa.Column('condicion_iibb_id', sa.Integer(), nullable=True))
    op.add_column('cliente', sa.Column('nro_iibb', sa.String(length=20), nullable=True))
    op.create_foreign_key(None, 'cliente', 'condiciontributaria', ['condicion_iva_id'], ['id'])
    op.create_foreign_key(None, 'cliente', 'condiciontributaria', ['condicion_iibb_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cliente', type_='foreignkey')
    op.drop_constraint(None, 'cliente', type_='foreignkey')
    op.drop_column('cliente', 'nro_iibb')
    op.drop_column('cliente', 'condicion_iibb_id')
    op.drop_column('cliente', 'condicion_iva_id')
    op.create_table('clienteimpuesto',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo_impuesto_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('aplica', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('alicuota', mysql.FLOAT(), nullable=True),
    sa.Column('observaciones', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('condicion_tributaria_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nro_inscripcion', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30), nullable=True),
    sa.Column('fecha_vencimiento_exencion', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name='clienteimpuesto_ibfk_1'),
    sa.ForeignKeyConstraint(['condicion_tributaria_id'], ['condiciontributaria.id'], name='clienteimpuesto_ibfk_3'),
    sa.ForeignKeyConstraint(['tipo_impuesto_id'], ['tipoimpuesto.id'], name='clienteimpuesto_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
