"""Agregar codigo_arca 

Revision ID: 90f4b178864c
Revises: 2c926e8e24a7
Create Date: 2025-06-18 00:04:38.591787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90f4b178864c'
down_revision: Union[str, None] = '2c926e8e24a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concepto', sa.Column('codigo_arca', sa.String(length=3), nullable=False))
    op.add_column('moneda', sa.Column('codigo_arca', sa.String(length=3), nullable=False))
    op.add_column('tipodoc', sa.Column('codigo_arca', sa.String(length=3), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tipodoc', 'codigo_arca')
    op.drop_column('moneda', 'codigo_arca')
    op.drop_column('concepto', 'codigo_arca')
    # ### end Alembic commands ###
