"""remove_condicion_iva_and_simplify_tax_cond_schema

Revision ID: a05fa68eda88
Revises: e28dcc063f66
Create Date: 2025-12-29 18:20:11.850359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a05fa68eda88'
down_revision: Union[str, None] = 'e28dcc063f66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('fk_cliente_condicioniva', 'cliente', type_='foreignkey')
    # op.drop_column('cliente', 'iva_id')
    # op.drop_index('ix_condicioniva_codigo', table_name='condicioniva')
    op.drop_table('condicioniva')
    op.drop_table('tipo_impuesto_condiciones')
    op.add_column('condiciontributaria', sa.Column('tipo_impuesto_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'condiciontributaria', 'tipoimpuesto', ['tipo_impuesto_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'condiciontributaria', type_='foreignkey')
    op.drop_column('condiciontributaria', 'tipo_impuesto_id')
    op.add_column('cliente', sa.Column('iva_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_cliente_condicioniva', 'cliente', 'condicioniva', ['iva_id'], ['id'])
    op.create_table('tipo_impuesto_condiciones',
    sa.Column('tipo_impuesto_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('condicion_tributaria_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['condicion_tributaria_id'], ['condiciontributaria.id'], name='tipo_impuesto_condiciones_ibfk_2'),
    sa.ForeignKeyConstraint(['tipo_impuesto_id'], ['tipoimpuesto.id'], name='tipo_impuesto_condiciones_ibfk_1'),
    sa.PrimaryKeyConstraint('tipo_impuesto_id', 'condicion_tributaria_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('condicioniva',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('codigo', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('descripcion', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_condicioniva_codigo', 'condicioniva', ['codigo'], unique=True)
    # ### end Alembic commands ###
