"""initial

Revision ID: a392b3b734a7
Revises: 
Create Date: 2025-12-14 20:57:33.100440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a392b3b734a7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concepto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=3), nullable=False),
    sa.Column('descripcion', sa.String(length=50), nullable=False),
    sa.Column('codigo_arca', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('iva',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=30), nullable=False),
    sa.Column('porcentaje', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('discriminado', sa.Boolean(), nullable=False),
    sa.Column('porcentaje_sobre', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iva_codigo'), 'iva', ['codigo'], unique=True)
    op.create_table('menuitem',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('path', sa.String(length=200), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['menuitem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moneda',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=3), nullable=False),
    sa.Column('descripcion', sa.String(length=50), nullable=False),
    sa.Column('codigo_arca', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('pais',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=2), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('rol',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rol_nombre', sa.String(length=50), nullable=False),
    sa.Column('es_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rol_nombre')
    )
    op.create_table('tipocomprobante',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=3), nullable=False),
    sa.Column('descripcion', sa.String(length=50), nullable=False),
    sa.Column('es_fiscal', sa.Boolean(), nullable=False),
    sa.Column('codigo_arca', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('tipodoc',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_doc_nombre', sa.String(length=30), nullable=False),
    sa.Column('habilitado', sa.Boolean(), nullable=False),
    sa.Column('codigo_arca', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo_doc_nombre')
    )
    op.create_table('tipodom',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipoimpuesto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo_afip', sa.String(length=3), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=False),
    sa.Column('tipo_aplicacion', sa.Enum('SUMA', 'DESCUENTO', 'NEUTRO', name='tipoaplicacionenum'), nullable=False),
    sa.Column('base_calculo', sa.Enum('SUBTOTAL', 'TOTAL', 'NETO_GRAVADO', 'OTROS', name='basetributarioenum'), nullable=False),
    sa.Column('porcentaje', sa.Float(), nullable=True),
    sa.Column('editable', sa.Boolean(), nullable=False),
    sa.Column('obligatorio', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_afip')
    )
    op.create_table('tipotel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_email', sa.String(length=50), nullable=False),
    sa.Column('usuario_password', sa.String(length=100), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('apellido', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_email')
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('razon_social', sa.String(length=100), nullable=True),
    sa.Column('cuit', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('tipo_doc_id', sa.Integer(), nullable=False),
    sa.Column('iva_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['iva_id'], ['iva.id'], ),
    sa.ForeignKeyConstraint(['tipo_doc_id'], ['tipodoc.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cuit')
    )
    op.create_table('provincia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provincia_nombre', sa.String(length=50), nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pais_id'], ['pais.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provincia_nombre')
    )
    op.create_table('rolesusuario',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'rol_id')
    )
    op.create_table('rolmenuitem',
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menuitem.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ),
    sa.PrimaryKeyConstraint('rol_id', 'menu_item_id')
    )
    op.create_table('clienteimpuesto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tipo_impuesto_id', sa.Integer(), nullable=False),
    sa.Column('aplica', sa.Boolean(), nullable=False),
    sa.Column('alicuota', sa.Float(), nullable=True),
    sa.Column('observaciones', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['tipo_impuesto_id'], ['tipoimpuesto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comprobante',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tipo_comprobante_id', sa.Integer(), nullable=False),
    sa.Column('concepto_id', sa.Integer(), nullable=False),
    sa.Column('tipo_doc_id', sa.Integer(), nullable=False),
    sa.Column('moneda_id', sa.Integer(), nullable=False),
    sa.Column('punto_venta', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('fecha_emision', sa.Date(), nullable=False),
    sa.Column('doc_nro', sa.String(length=20), nullable=False),
    sa.Column('nombre_cliente', sa.String(length=100), nullable=False),
    sa.Column('cuit_cliente', sa.String(length=20), nullable=False),
    sa.Column('domicilio_cliente', sa.String(length=100), nullable=False),
    sa.Column('localidad_cliente', sa.String(length=50), nullable=False),
    sa.Column('cod_postal_cliente', sa.String(length=10), nullable=True),
    sa.Column('provincia_cliente', sa.String(length=50), nullable=False),
    sa.Column('cotizacion_moneda', sa.Float(), nullable=False),
    sa.Column('total_neto', sa.Float(), nullable=False),
    sa.Column('total_iva', sa.Float(), nullable=False),
    sa.Column('total_impuestos', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('observaciones', sa.String(length=255), nullable=True),
    sa.Column('cae', sa.String(length=50), nullable=False),
    sa.Column('cae_vencimiento', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['concepto_id'], ['concepto.id'], ),
    sa.ForeignKeyConstraint(['moneda_id'], ['moneda.id'], ),
    sa.ForeignKeyConstraint(['tipo_comprobante_id'], ['tipocomprobante.id'], ),
    sa.ForeignKeyConstraint(['tipo_doc_id'], ['tipodoc.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('localidad',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('localidad_nombre', sa.String(length=50), nullable=False),
    sa.Column('cod_postal', sa.String(length=15), nullable=False),
    sa.Column('provincia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['provincia_id'], ['provincia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operador',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auditoriacomprobante',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comprobante_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=20), nullable=False),
    sa.Column('detalle', sa.String(length=255), nullable=True),
    sa.Column('ip_origen', sa.String(length=50), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comprobante_id'], ['comprobante.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comprobantedetalle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comprobante_id', sa.Integer(), nullable=False),
    sa.Column('iva_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('importe', sa.Float(), nullable=False),
    sa.Column('alicuota_iva', sa.Float(), nullable=False),
    sa.Column('importe_iva', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['comprobante_id'], ['comprobante.id'], ),
    sa.ForeignKeyConstraint(['iva_id'], ['iva.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comprobanteimpuesto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comprobante_id', sa.Integer(), nullable=False),
    sa.Column('tipo_impuesto_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=False),
    sa.Column('base_imponible', sa.Float(), nullable=False),
    sa.Column('alicuota', sa.Float(), nullable=False),
    sa.Column('importe', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['comprobante_id'], ['comprobante.id'], ),
    sa.ForeignKeyConstraint(['tipo_impuesto_id'], ['tipoimpuesto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cuentacorriente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('comprobante_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('importe', sa.Float(), nullable=False),
    sa.Column('signo', sa.Integer(), nullable=False),
    sa.Column('saldo', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['comprobante_id'], ['comprobante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domicilio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('calle', sa.String(length=60), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tipo_dom_id', sa.Integer(), nullable=False),
    sa.Column('localidad_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['localidad_id'], ['localidad.id'], ),
    sa.ForeignKeyConstraint(['tipo_dom_id'], ['tipodom.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telefono',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_tel_id', sa.Integer(), nullable=False),
    sa.Column('prefijo', sa.String(length=10), nullable=False),
    sa.Column('numero', sa.String(length=12), nullable=False),
    sa.Column('domicilio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['domicilio_id'], ['domicilio.id'], ),
    sa.ForeignKeyConstraint(['tipo_tel_id'], ['tipotel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telefono')
    op.drop_table('domicilio')
    op.drop_table('cuentacorriente')
    op.drop_table('comprobanteimpuesto')
    op.drop_table('comprobantedetalle')
    op.drop_table('auditoriacomprobante')
    op.drop_table('operador')
    op.drop_table('localidad')
    op.drop_table('comprobante')
    op.drop_table('clienteimpuesto')
    op.drop_table('rolmenuitem')
    op.drop_table('rolesusuario')
    op.drop_table('provincia')
    op.drop_table('cliente')
    op.drop_table('usuario')
    op.drop_table('tipotel')
    op.drop_table('tipoimpuesto')
    op.drop_table('tipodom')
    op.drop_table('tipodoc')
    op.drop_table('tipocomprobante')
    op.drop_table('rol')
    op.drop_table('pais')
    op.drop_table('moneda')
    op.drop_table('menuitem')
    op.drop_index(op.f('ix_iva_codigo'), table_name='iva')
    op.drop_table('iva')
    op.drop_table('concepto')
    # ### end Alembic commands ###
