"""increase_tipoimpuesto_nombre_length

Revision ID: d3a9dab8ccfb
Revises: a392b3b734a7
Create Date: 2025-12-29 13:40:59.904694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd3a9dab8ccfb'
down_revision: Union[str, None] = 'a392b3b734a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_iva_codigo'), 'iva', ['codigo'], unique=True)
    op.alter_column('tipoimpuesto', 'nombre',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tipoimpuesto', 'nombre',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=False)
    op.drop_index(op.f('ix_iva_codigo'), table_name='iva')
    # ### end Alembic commands ###
