"""Add tax redesign fields

Revision ID: ecdb8ab51ad1
Revises: d3a9dab8ccfb
Create Date: 2025-12-29 17:01:13.850492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecdb8ab51ad1'
down_revision: Union[str, None] = 'd3a9dab8ccfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clienteimpuesto', sa.Column('condicion_tributaria_id', sa.Integer(), nullable=True))
    op.add_column('clienteimpuesto', sa.Column('nro_inscripcion', sa.String(length=30), nullable=True))
    op.add_column('clienteimpuesto', sa.Column('fecha_vencimiento_exencion', sa.Date(), nullable=True))
    op.create_foreign_key(None, 'clienteimpuesto', 'condiciontributaria', ['condicion_tributaria_id'], ['id'])
    op.add_column('tipoimpuesto', sa.Column('ambito', sa.Enum('NACIONAL', 'PROVINCIAL', 'MUNICIPAL', name='ambitoimpuestoenum'), nullable=False))
    op.add_column('tipoimpuesto', sa.Column('categoria', sa.Enum('IMPUESTO_DIRECTO', 'PERCEPCION', 'RETENCION', 'TASA', name='categoriaimpuestoenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tipoimpuesto', 'categoria')
    op.drop_column('tipoimpuesto', 'ambito')
    op.drop_constraint(None, 'clienteimpuesto', type_='foreignkey')
    op.drop_column('clienteimpuesto', 'fecha_vencimiento_exencion')
    op.drop_column('clienteimpuesto', 'nro_inscripcion')
    op.drop_column('clienteimpuesto', 'condicion_tributaria_id')
    # ### end Alembic commands ###
