"""fix_comprobante_numero_constraint

Revision ID: eed577e30087
Revises: b5fd2f1d24db
Create Date: 2026-02-04 20:06:39.336586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'eed577e30087'
down_revision: Union[str, None] = 'b5fd2f1d24db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('numero', table_name='comprobante')
    op.create_unique_constraint('uq_comprobante_numero', 'comprobante', ['tipo_comprobante_id', 'punto_venta', 'numero'])
    op.alter_column('tipoimpuesto', 'codigo_afip',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=False)
    op.alter_column('tipoimpuesto', 'nombre',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tipoimpuesto', 'nombre',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=True)
    op.alter_column('tipoimpuesto', 'codigo_afip',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=True)
    op.drop_constraint('uq_comprobante_numero', 'comprobante', type_='unique')
    op.create_index('numero', 'comprobante', ['numero'], unique=True)
    # ### end Alembic commands ###
